apiVersion: v1
kind: Pod
metadata:
  labels:
    component: litekube
    tier: control-plane
  name: litekube
  namespace: kube-system
spec:
  priorityClassName: system-node-critical
  hostNetwork: true
  volumes:
  - name: etcd-certs
    hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
  - name: litekube-data
    hostPath:
      path: /var/lib/litekube
      type: DirectoryOrCreate
  containers:
  - name: litekube
    image: ghcr.io/arhat-dev/litekube:latest-alpine
    imagePullPolicy: Always
    env:
    - name: DEBUG_KINE
      value: "false"
    args:
    - run
    securityContext:
      privileged: true
      capabilities:
        add:
        # for keepalived vrrp
        - NET_ADMIN
        # for flock
        # - LEASE
        drop:
        - ALL
    volumeMounts:
    - mountPath: /data
      name: litekube-data
      mountPropagation: Bidirectional
    - mountPath: /etcd-certs
      name: etcd-certs
    resources: {}
    ports:
    - name: etcd-client
      containerPort: 12379
    # litestream metrics
    - name: ls-metrics
      containerPort: 19090
    # livenessProbe:
    #   failureThreshold: 8
    #   httpGet:
    #     host: 127.0.0.1
    #     path: /health
    #     port: 12379
    #     scheme: HTTP
    #   initialDelaySeconds: 10
    #   periodSeconds: 10
    #   timeoutSeconds: 15
    # startupProbe:
    #   failureThreshold: 24
    #   httpGet:
    #     host: 127.0.0.1
    #     path: /health
    #     port: 12379
    #     scheme: HTTP
    #   initialDelaySeconds: 10
    #   periodSeconds: 10
    #   timeoutSeconds: 15
