name: CI

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  pull_request:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    - "!deps/**"
  push:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    tags:
    - v*

defaults:
  run:
    shell: bash

jobs:
  build-images:
    if: contains(github.head_ref, 'deps/') == false
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Install qemu-static
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        sudo apt update
        sudo apt install -y qemu-user-static

    - name: Install dukkha
      run: |-
        mkdir -p "${HOME}/bin"
        echo "${HOME}/bin" >> $GITHUB_PATH

        docker pull ghcr.io/arhat-dev/dukkha:latest
        ctr_id=$(docker create ghcr.io/arhat-dev/dukkha:latest : 2>/dev/null)
        docker cp ${ctr_id}:/dukkha "${HOME}/bin/dukkha"

        chmod +x "${HOME}/bin/dukkha"

    - name: Build Tools
      run: |-
        dukkha golang github-docker build litestream
        dukkha golang github-docker build kine

    - name: Build and Push Images
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        GITHUB_DOCKER_USERNAME: ${{ github.actor }}
        GITHUB_DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        buildah login -u="${DOCKERHUB_USERNAME}" -p="${DOCKERHUB_PASSWORD}" docker.io
        buildah login -u="${GITHUB_DOCKER_USERNAME}" -p="${GITHUB_DOCKER_PASSWORD}" ghcr.io

        dukkha buildah bud litekube
        dukkha buildah push litekube
